## Makefile
# p3: pypy3 -m py_compile
CXX = g++
CXXFLAGS = -Wall -Wconversion -Wfatal-errors -g -O2
-std=gnu++20 -fsanitize=address,undefined -Wshadow
-fno-omit-frame-pointer -Wno-unused-result
-Wno-sign-compare -Wno-char-subscripts #-fuse-ld=gold
